services:
  fraud_engine:
    image: postgres:16-alpine
    container_name: fraud_db
    environment:
      POSTGRES_USER: fraud_engine
      POSTGRES_PASSWORD: g2lY<o?l'p[pJg8b[\3;vp2X%~(
      POSTGRES_DB: fraud_db
    ports:
      - "5432:5432"
    volumes:
      - fraud_db:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U fraud_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  user_management:
    image: postgres:16-alpine
    container_name: user_management
    environment:
      POSTGRES_USER: user_management
      POSTGRES_PASSWORD: 9)rR2cXsN>|Btb,v/QxL5Y7V*l
      POSTGRES_DB: user_management
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - user_management:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_management" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      user_management:
        condition: service_healthy
      fraud_engine:
        condition: service_healthy
    container_name: fraud_engine
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      FRAUD_JDBC_URL: jdbc:postgresql://fraud_engine:5432/fraud_db
      FRAUD_DB_USERNAME: fraud_engine
      FRAUD_DB_PASSWORD: g2lY<o?l'p[pJg8b[\3;vp2X%~(

      USER_JDBC_URL: jdbc:postgresql://user_management:5433/user_management
      USER_DB_USERNAME: user_management
      USER_DB_PASSWORD: 9)rR2cXsN>|Btb,v/QxL5Y7V*l

volumes:
  user_management:
    driver: local
  fraud_db:
    driver: local
